name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -scheme SPMDepNetrc-Package -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' clean build
